<a href="https://colab.research.google.com/github/phs-lab/preliminary/blob/master/Summaries%26CheatsheetsCollected.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone "https://github.com/phs-lab/preliminary.git"

Cloning into 'preliminary'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 255 (delta 25), reused 0 (delta 0), pack-reused 213
Receiving objects: 100% (255/255), 4.02 MiB | 3.33 MiB/s, done.
Resolving deltas: 100% (118/118), done.


In [2]:
%run -i ./preliminary/myLibClass.py
# %run -i D:/Github/repository/myLibClass.py

▣ 자주 사용하는 Python Module : np, sp, plt, sns, os, re, sys, sklearn, sqlite3→runSQL(,cursor), pd ☞ my.fum() 
    - %magic, %lsmagic %pinfo %env %store %%script ☞ https://ipython.readthedocs.io/en/stable/interactive/magics.html 
    - myLibInfo ★, help(), □? □?? Shift+Tab Shift+Tab(수회),dir(),%whos,[List],(Tuple,),{Set},{'d':'Dict'}
【rpy2】 3.2.7 : 최초⇒'%load_ext rpy2.ipython', 다시 load(내부 R 세션 시작)⇒'%reload_ext rpy2.ipython'; %Rㆍ%%R == ro.r('R Script')
 %Rget,%R -i,%Rpush ⇔ %R -o,%Rpull ☞『df』 ①py⇒r:ro.r.assign('R.df',ro.pandas2ri.py2ri(PYdf)), ②r⇒py:PYdf=ro.pandas2ri.ri2py(R.df)


# Python

## 일반

▣ python web references : python → numpy → pandas → sqlite → pycaret → scikit-learn → auto-keras → keras → tensorflow  
+ [python.org](https://docs.python.org/) references &nbsp; &nbsp; ☞ [코딩 도장](https://dojang.io/course/view.php?id=7) &nbsp; [Jump to Python](https://wikidocs.net/book/1)
  - [operator precedence](https://docs.python.org/3/reference/expressions.html#operator-precedence), [코딩 도장](https://dojang.io/mod/page/view.php?id=2461)
+ numpy
+ scipy
+ pandas
+ scikit-learn
  - [chooling the right estimator](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html)
+ keras
+ tensorflow

▣ 유용한 Site URLs  
- 마크다운 : [MathJax에서 유용한 Tex 명령어](http://www.onemathematicalcat.org/MathJaxDocumentation/MathJaxKorean/TeXSyntax_ko.html) &nbsp; [위키백과:TeX 문법](https://ko.wikipedia.org/wiki/위키백과:TeX_문법) &nbsp; [MathJax 도움말](http://docs.mathjax.org/en/latest/) &nbsp; [사례](https://blog.naver.com/dkdldoafotn/221679509761)
- network diagram : https://networkx.github.io/documentation/latest/tutorial.html
- 김태완님 blog : numpy [cheat sheet](http://taewan.kim/post/numpy_cheat_sheet/) [axis](http://taewan.kim/post/numpy_sum_axis/), 머신러닝 [ML](http://taewan.kim/categories/machine-learning/)

In [ ]:
!python --version

Python 3.6.9


In [ ]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [ ]:
import keyword
keyword.kwlist.sort()
for cnt, item in zip(range(1,len(keyword.kwlist)+1), keyword.kwlist):
  print(item) if cnt%9 == 0 else print(item, end='\t')
else:
  print('☞ Total', cnt, 'items')

False	None	True	and	as	assert	break	class	continue
def	del	elif	else	except	finally	for	from	global
if	import	in	is	lambda	nonlocal	not	or	pass
raise	return	try	while	with	yield	☞ Total 33 items


append( ), clear( ), remove( ) method가 있는 collection이 mutables인 듯...

|구분1   |구분2          |자료형    |컬렉션<Br>(컨테이너)|이질/등질|가변/불변|예시|
|:-------|:--------------|:---------|:---------:|:---:|:---:|:----------|
|숫자형  |               |bool      | Χ | Χ |불변|    |
|        |               |int       | Χ | Χ |불변|    |
|        |               |float     | Χ | Χ |불변|    |
|        |               |complex   | Χ | Χ |불변|    |
|시퀀스형|문자형-텍스트  |str       | ○ |등질|불변|'1행', "1행", '''복수 행''', """복수 행"""    |
|        |문자형-바이너리|bytes     | ○ |등질|불변|    |
|        |문자형-바이너리|bytearray | ○ |등질|***가변***|    |
|시퀀스형|               |range     | ○ |등질|불변|range(start,stop,step) `#` start $\le$ value $\lt$ stop|
|        |               |tuple ( , ) | ○ |***이질***|불변|    |
|        |               |list  [ ] | ○ |***이질***|***가변***|    |
|매핑형  |               |dict {key:value}| ○ |***이질***|***가변***|    |
|집합형  |               |set   { } | ○ |***이질***|***가변***|    |
|        |               |frozenset | ○ |***이질***|불변|    |

▣ Python control structures  

|if - else|for|while|[try](https://dojang.io/mod/page/view.php?id=2398)|
|:----|:----|:----|:----|
|**if** condition:<Br>&nbsp; &nbsp; expression<Br>**elif** condition:<Br>&nbsp; &nbsp; expression<Br>**else**:<Br>&nbsp; &nbsp; expression<Br><Br>|**for** item **in** *collection*:<Br>&nbsp; &nbsp; expression<Br>**else:** `#` 항상 실행<Br>&nbsp; &nbsp; expression<Br><Br><Br><Br>|**while** condition:<Br>&nbsp; &nbsp; expression<Br>**else:** `#` 항상 실행<Br>&nbsp; &nbsp; expression<Br><Br><Br><Br>|**try:**<Br>&nbsp; &nbsp; expression<Br>**except:** `#` 예외 有, 이름 특정 가능<Br>&nbsp; &nbsp; expression<Br>**else:** `#` 예외 無<Br>&nbsp; &nbsp; expression<Br>**finally:** `#` 항상 실행<Br>&nbsp; &nbsp; expression|

## numpy

## scipy

## sympy

## pandas

## pycaret

## scikit-learn

![https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html](https://scikit-learn.org/stable/_static/ml_map.png)

In [ ]:
print(ChooseRightSklearnEstimator(...)) # https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

('url for choosing the right estimator', 'https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html')


In [ ]:
print(ChooseRightSklearnEstimator(1000, 'C', True)[1])

Linear SVC	☞ 잘 안되면,	(Text면) NaiveBayes,
				(아니면) KNeighborsClassifier ☞ 잘 안되면, SVC 또는 EnsembleClassifiers


## keras

## tensorflow

# R

In [ ]:
# ① 최초 Session : %load_ext rpy2.ipython ; ② Session 재시작 : %reload_ext rpy2.ipython
%load_ext rpy2.ipython

In [ ]:
# OS Command 사용 사례: https://stat.ethz.ch/R-manual/R-devel/library/base/html/system.html
# %R system("git clone 'https://github.com/youngwoos/Doit_R.git'", intern = TRUE)

In [4]:
%R pkg <- c('data.table'); pkg[(pkg %in% installed.packages()[, "Package"])]

array([], dtype=float64)

In [ ]:
%R install.packages('data.table')

In [6]:
%R pkg <- c('data.table'); pkg[(pkg %in% installed.packages()[, "Package"])]

array(['data.table'], dtype='<U10')

In [7]:
%R require('data.table')

R[write to console]: Loading required package: data.table



array([1], dtype=int32)

In [8]:
%%R
ReqPkgs <- function(pkgs, require.flag=FALSE){  # http://randpython.blogspot.com/2018/01/r.html
  new.pkgs <- pkgs[!(pkgs %in% installed.packages()[, "Package"])]
  if (length(new.pkgs))  # 참고, 기설치 확인 : pkgs[(pkgs %in% installed.packages()[, "Package"])]
    install.packages(new.pkgs, dependencies = TRUE)
  if (require.flag)
    sapply(pkgs, require, character.only = TRUE)
}

```R
pkgs <- c("a_package","b_package","c_package")  # 설치하고 불러 올 패키지 정의
ReqPkgs(pkgs)                                   # 설치 및 불러오기 실행
```

In [ ]:
# https://stackoverflow.com/questions/20596786/rstudio-is-it-possible-to-run-a-code-in-the-background
# %R ReqPkgs(c('tidymodels', 'caret','tesseract'))  # jmv : 장시간 제외. DescTools: 윈도우용인듯. ∴ 코랩에서 처리 제외

In [9]:
%R require(tidyverse)

R[write to console]: Loading required package: tidyverse

R[write to console]: ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──

R[write to console]: ✔ ggplot2 3.3.2     ✔ purrr   0.3.4
✔ tibble  3.0.4     ✔ dplyr   1.0.2
✔ tidyr   1.1.2     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.0

R[write to console]: ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::between()   masks data.table::between()
✖ dplyr::filter()    masks stats::filter()
✖ dplyr::first()     masks data.table::first()
✖ dplyr::lag()       masks stats::lag()
✖ dplyr::last()      masks data.table::last()
✖ purrr::transpose() masks data.table::transpose()



array([1], dtype=int32)

## Base R

* https://rstudio.com/resources/cheatsheets/ ; https://ugoproto.github.io/ugo_r_doc/basics_cs/
* https://rfriend.tistory.com/14

![https://ugoproto.github.io/ugo_r_doc/basics_cs/](https://ugoproto.github.io/ugo_r_doc/img/base_r_cs/baseR-cheat-sheet-3a.png)

![https://ugoproto.github.io/ugo_r_doc/basics_cs/](https://ugoproto.github.io/ugo_r_doc/img/base_r_cs/baseR-cheat-sheet-3b.png)

**1. Getting Help**  
**1.1 Accessing the help files** 
- ?mean # get help of a particular function 'mean'.
- help.search('weighted mean') # Search the help files for a word or phrase.
- help(package='dplyr') # Find help for a package.  

**1.2 More about an object**  
- str(iris) # Get a summary of an object’s structure.
- class(iris) # Find the class an object belongs to.

**2. Using Packages**  
- install.packages('dplyr') # Download and install a package from CRAN.
- library(dplyr) # Load the package into the session, making all its functions available to use.
- require(dplyr) # library와 같은 효과. Return값으로 실행 결과 판단 가능.
- dplyr::select # Use a particular function from a package.
- data(iris) # Load a built-in dataset into the environment.

**3. Working Directory**  
- getwd() : Find the current working directory (where
inputs are found and outputs are sent).
- setwd('C://file/path') # Change the current working directory.

&nbsp; &nbsp; &nbsp; Use projects in RStudio to set the working directory to the folder you are working in.

**4. The Environment**  
- ls( ) # List all variables in the environment.
- rm(x) # Remove x from the environment.
- rm(list = ls( )) # Remove all variables from the environment.

&nbsp; &nbsp; &nbsp; You can use the environment panel in RStudio to browse variables in your environment.

**5. Variable Assignment** 
```R
> a <- 'apple' # 문자열 'apple'을 변수 a에 할당. 『 a = 'apple' 』도 같은 표현임.
> a
  [1] 'apple'
```

**6. Data Types**  
![https://rfriend.tistory.com/14](https://t1.daumcdn.net/cfile/tistory/230EBE375672CF0337)

**6.1 Vectors**  
6.1.1 Creating Vectors  

|R Script|Result|Explanation|
|:---|:---|:---|
|c(2, 4, 6)|2 4 6|Join elements into a vector|
|2:6|2 3 4 5 6|An integer sequence|
|seq(2, 3, by=0.5)|2.0 2.5 3.0|A complex sequence|
|rep(1:2, times=3)|1 2 1 2 1 2|Repeat a vector   |
|rep(1:2, each=3) |1 1 1 2 2 2|Repeat elements of a vector|

6.1.2 Vector Functions  

|sort(x)|rev(x)|table(x)|unique(x)|
|:---|:---|:---|:---|
|Return x sorted.|Return x reversed.|See counts of values.|See unique values.|

6.1.3 Selecting Vector Elemnets  

|By Position||By Value||Named Vectors||
|:---|:---|:---|:---|:---|:---|
|x[4]|The fourth element.|x[x == 10]|Elements which are equal to 10.|x['apple']|Element with name 'apple'.|
|x[-4]|All but the fourth.|x[x < 0]|All elements less than zero.|||
|x[2:4]|Elements two to four.|x[x %in% c(1, 2, 5)]|Elements in the set 1, 2, 5.|||
|x[-(2:4)]|All elements except two to four.|||||
|x[c(1, 5)]|Elements one and five.|||||

**6.2 Matrices**

|Matrices Handling|Explanation|Matrices Handling|Explanation|
|:---|:---|:---|:---|
|m <- matrix(x, nrow = 3, ncol = 3)|Create a matrix from x.|||
|m[2, ]|Select a row     |t(m)      |Transpose            |
|m[ ,1]|Select a column  |m %*% n   |Matrix Multiplication|
|m[2,3]|Select an element|solve(m,n)|Find x in: m * x = n |

**6.3 Lists**

In [ ]:
%R l <- list(x = 1:5, y = c('a', 'b')); print(l) # A list is a collection of elements which can be of different types.

$x
[1] 1 2 3 4 5

$y
[1] "a" "b"



R object with classes: ('list',) mapped to:
[IntSexpVector, StrSexpVector]
  x: <class 'rpy2.rinterface.IntSexpVector'>
  <rpy2.rinterface.IntSexpVector object at 0x7fd8a02d8488> [RTYPES.INTSXP]
  y: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x7fd8a4dbee88> [RTYPES.STRSXP]

In [ ]:
%R l[[2]] # Second element of l.

array(['a', 'b'], dtype='<U1')

In [ ]:
%R l$x # Element named x.

array([1, 2, 3, 4, 5], dtype=int32)

In [ ]:
%R l['y'] # New list with only element named y.

R object with classes: ('list',) mapped to:
[StrSexpVector]
  y: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x7fd8a4dfbf08> [RTYPES.STRSXP]

**6.4 Data Frames**

In [ ]:
# Data frame is a special case of a list where all elements are the same length.
%R df <- data.frame(x = 1:3, y = c('a', 'b', 'c')); df

|data.frame|df|Subsetting||Functions||
|:--:|:--:|:---|:---|:---|:---|
|x열|y열|&nbsp; List `~`||View(df)|See the full data frame.|
|1|a|&nbsp; &nbsp; &nbsp; df$x|x열 반환|head(df)|See the first 6 rows.|
|2|b|&nbsp; &nbsp; &nbsp; df[[2]]|y열 반환|nrow(df)|Number of rows|
|3|c|&nbsp; Matrix `~`||ncol(df)|Number of columns.|
|||&nbsp; &nbsp; &nbsp; df[2, ]|2번째 행(2, b) 반환|dim(df)|Number of columns and rows.|
|||&nbsp; &nbsp; &nbsp; df[ ,2]|y열 반환|cbind(df1, df2)|Bind columns. (행 수가 같아야 함 ?)|
|||&nbsp; &nbsp; &nbsp; df[2,2]|원소 b 반환|rbind(df3, df4)|Bind rows. (열 수가 같아야 함 ?)|

**6.5 Strings**

In [ ]:
%R x <- 'Strings related examples'; y <- 'in base R cheatsheet!'
%R paste(x, y, sep = ' ') # Join multiple vectors together.

array(['Strings related examples in base R cheatsheet!'], dtype='<U46')

In [ ]:
%R paste(x, collapse = ' ') # Join elements of a vector together.

array(['Strings related examples'], dtype='<U24')

In [ ]:
%R pattern <- '^[a-zA-Z]'; grep(pattern, x) # Find regular expression matches in x.

array([1], dtype=int32)

In [ ]:
%R pattern <- 'a'; replace <- 'A'; gsub(pattern, replace, x) # Replace matches in x with a string.

array(['Strings relAted exAmples'], dtype='<U24')

In [ ]:
%R toupper(x) # Convert to uppercase.

array(['STRINGS RELATED EXAMPLES'], dtype='<U24')

In [ ]:
%R tolower(x) # Convert to lowercase.

array(['strings related examples'], dtype='<U24')

In [ ]:
%R nchar(x) # Number of characters in a string.

array([24], dtype=int32)

In [ ]:
%%R
CapStr <- function(y) {  
  c <- strsplit(y, " ")[[1]]
  paste(toupper(substring(c, 1,1)), substring(c, 2),
      sep="", collapse=" ")
} # https://rstudio-pubs-static.s3.amazonaws.com/408658_512da947714740b99253228f084a08a9.html

x <- c("sepal length", "sepal width",  "petal length", "petal width",  "species")

In [ ]:
%R sapply(x, CapStr)

array(['Sepal Length', 'Sepal Width', 'Petal Length', 'Petal Width',
       'Species'], dtype='<U12')

**6.6 Factors**  
- factor(x) # Turn a vector into a factor. Can set the levels of the factor and the order.
- cut(x, breaks = 4) # Turn a numeric vector into a factor by 'cutting' into sections.

**6.7 Types**  
Converting between common data types in R. Can always go
from a higher value in the table to a lower value.

|R Script         |Value            |Explanation|
|:---|:---|:---|
|as.logical       |TRUE, FALSE, TRUE|Boolean values (TRUE or FALSE).                   |
|as.numeric       |1, 0, 1          |Integers or floating point numbers.               |
|as.character     |'1', '0', '1'    |Character strings. Generally preferred to factors.|
|as.factor<Br><Br>|'1', '0', '1',<Br>levels: '1', '0'|Character strings with preset levels. Needed for some statistical models.<Br><Br>|

In [ ]:
%R is(df)  # is.logical, is.numeric, is.character, is.factor 사용 가능함

array(['data.frame', 'list', 'oldClass', 'vector'], dtype='<U10')

**7. Programming**  

||for Loop|while Loop|if Statements|function|Conditions|
|:---|:---|:---|:---|:---|:---|
|Syntax<Br><Br><Br><Br><Br>|for (variable in sequence) {<Br>&nbsp; &nbsp; Do something<Br>}<Br><Br><Br>|while (condition){<Br>&nbsp; &nbsp; Do something<Br>}<Br><Br><Br>|if (condition) {<Br>&nbsp; &nbsp; Do something<Br>} else {<Br>&nbsp; &nbsp; Do something different<Br>}|function_name <- function(var {<Br>&nbsp; &nbsp; Do something<Br>&nbsp; &nbsp; return(new_variable)<Br>}<Br><Br>|a == b<Br>a > b<Br>a >= b<Br>is.na(a) # is 'a' missing?<Br><Br>|
|Example<Br><Br><Br><Br><Br>|for (i in 1:4) {<Br>&nbsp; &nbsp; j <- i + 10<Br>&nbsp; &nbsp; print(j)<Br>}<Br><Br>|while (i < 5) {<Br>&nbsp; &nbsp; print(i)<Br>&nbsp; &nbsp; i <- i + 1<Br>}<Br><Br>|if (i > 3) {<Br>&nbsp; &nbsp; print(‘Yes’)<Br>} else {<Br>&nbsp; &nbsp; print(‘No’)<Br>}|square <- function(x) {<Br>&nbsp; &nbsp; squared <- x*x<Br>&nbsp; &nbsp; return(squared)<Br>}<Br><Br>|a != b<Br>a < b<Br>a <= b<Br>is.null(a) # is 'a' null?<Br><Br>|

**8. Reading & Writing Data**  
- Also see the readr package.

|Input|Output|Description|
|:---|:---|:---|
|df <- read.table(‘file.txt')|write.table(df, ‘file.txt')|Read and write a delimited text file.|
|df <- read.csv(‘file.csv')|write.csv(df, ‘file.csv')|Read and write a comma separated value file. This is a special case of read.table/write.table.|
|load(‘file.RData')|save(df, file = 'file.Rdata')|Read and write an R data file, a file type special for R.|

**9. Math Functions**  

|Function|Description|Function|Description|Function|Description|Function|Description|
|:---|:---|:---|:---|:---|:---|:---|:---|
|log(x)|Natural log.|sum(x)|Sum.|sd(x)|The standard deviation.|round(x, n)|Round to n decimal places.|
|exp(x)|Exponential.|mean(x)|Mean.|var(x)|The variance.|signif(x, n)|Round to n significant figures.|
|max(x)|Largest element.|median(x)|Median.|cor(x, y)|Correlation.|||
|min(x)|Smallest element.|quantile(x)|Percentage quantiles.|rank(x)|Rank of elements.|||

**10. Statistics**  
- lm(y ~ x, data=df) # Linear model.
- glm(y ~ x, data=df) # Generalised linear model.
- summary(result) # Get more detailed information out a model.
- t.test(x, y) # Perform a t-test for difference between means.
- pairwise.t.test # Perform a t-test for paired data.
- prop.test # Test for a difference between proportions.
- aov # Analysis of variance.

**11. Distributions**  

||Random Variates|Density Function|Cumulative Distribution|Quantile|
|:---:|:---:|:---:|:---:|:---:|
|Normal|rnorm|dnorm|pnorm|qnorm|
|Poisson|rpois|dpois|ppois|qpois|
|Binomial|rbinom|dbinom|pbinom|qbinom|
|Uniform|runif|dunif|punif|qunif|

## Syntax Comparison

* https://rstudio.com/resources/cheatsheets/ ; https://ugoproto.github.io/ugo_r_doc/specializations_cs/

![](https://ugoproto.github.io/ugo_r_doc/img/specialization_cs/syntaxa.png)

![](https://ugoproto.github.io/ugo_r_doc/img/specialization_cs/syntaxb.png)

## data.table
* https://cran.r-project.org/web/packages/data.table/ → [Intro. to data.table](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html)
* https://rstudio.com/resources/cheatsheets/ ; https://ugoproto.github.io/ugo_r_doc/specializations_cs/
* pandas vs. data.table – A study of data-frames
  + https://www.r-bloggers.com/2018/02/pandas-vs-data-table-a-study-of-data-frames/
  + https://www.r-bloggers.com/2018/03/pandas-vs-data-table-a-study-of-data-frames-part-2/

### Cheatsheet

![https://ugoproto.github.io/ugo_r_doc/specializations_cs/](https://ugoproto.github.io/ugo_r_doc/img/specialization_cs/datatablea.png)

![https://ugoproto.github.io/ugo_r_doc/specializations_cs/](https://ugoproto.github.io/ugo_r_doc/img/specialization_cs/datatableb.png)

### vignettes : [Introduction](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html)

**Data**

In [10]:
%%R
input <- if (file.exists("flights14.csv")) {
   "flights14.csv"
} else {
  "https://raw.githubusercontent.com/Rdatatable/data.table/master/vignettes/flights14.csv"
}
flights <- fread(input)

In [13]:
%R str(flights)

Classes ‘data.table’ and 'data.frame':	253316 obs. of  11 variables:
 $ year     : int  2014 2014 2014 2014 2014 2014 2014 2014 2014 2014 ...
 $ month    : int  1 1 1 1 1 1 1 1 1 1 ...
 $ day      : int  1 1 1 1 1 1 1 1 1 1 ...
 $ dep_delay: int  14 -3 2 -8 2 4 -2 -3 -1 -2 ...
 $ arr_delay: int  13 13 9 -26 1 0 -18 -14 -17 -14 ...
 $ carrier  : chr  "AA" "AA" "AA" "AA" ...
 $ origin   : chr  "JFK" "JFK" "JFK" "LGA" ...
 $ dest     : chr  "LAX" "LAX" "LAX" "PBI" ...
 $ air_time : int  359 363 351 157 350 339 338 356 161 349 ...
 $ distance : int  2475 2475 2475 1035 2475 2454 2475 2475 1089 2422 ...
 $ hour     : int  9 11 19 7 13 18 21 15 15 18 ...
 - attr(*, ".internal.selfref")=<externalptr> 


In [14]:
%R flights %>% head(3)

year  month  day  dep_delay  arr_delay  ... origin dest air_time  distance  hour
1  2014      1    1         14         13  ...    JFK  LAX      359      2475     9
2  2014      1    1         -3         13  ...    JFK  LAX      363      2475    11
3  2014      1    1          2          9  ...    JFK  LAX      351      2475    19

[3 rows x 11 columns]

**Introduction**  
**1. Basics**  
**1-a) What is data.table?**

data.table is an R package that provides an enhanced version of **data.frame**s, which are the standard data structure for storing data in base R. In the [Data section](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html#data) above, we already created a data.table using fread( ). We can also create one using the data.table( ) function. Here is an example:

In [ ]:
%%R
DT = data.table(
  ID = c("b","b","b","a","a","c"),
  a = 1:6,
  b = 7:12,
  c = 13:18
)

In [ ]:
%R DT

ID  a   b   c
1  b  1   7  13
2  b  2   8  14
3  b  3   9  15
4  a  4  10  16
5  a  5  11  17
6  c  6  12  18

In [ ]:
%R class(DT$ID)

array(['character'], dtype='<U9')

You can also convert existing objects to a data.table using `setDT( )` (for **data.frame**s and **list**s) and **as.data.table( )** (for other structures); the difference is beyond the scope of this vignette, see **?setDT** and **?as.data.table** for more details.

Note that:
- Unlike data.frames, columns of character type are never converted to factors by default.
- Row numbers are printed with a : in order to visually separate the row number from the first column.
- When the number of rows to print exceeds the global option datatable.print.nrows (default = 100), it automatically prints only the top 5 and bottom 5 rows (as can be seen in the Data section). If you’ve had a lot of experience with data.frames, you may have found yourself waiting around while larger tables print-and-page, sometimes seemingly endlessly. You can query the default number like so:
  ```R
  getOption("datatable.print.nrows")
  ```
- data.table doesn’t set or use row names, ever. We will see why in the “Keys and fast binary search based subset” vignette.


## dplyr : Data Transformation

![https://ugoproto.github.io/ugo_r_doc/specializations_cs/](https://ugoproto.github.io/ugo_r_doc/img/specialization_cs/dplyra.png)

![https://ugoproto.github.io/ugo_r_doc/specializations_cs/](https://ugoproto.github.io/ugo_r_doc/img/specialization_cs/dplyrb.png)

## Advanced R

* https://rstudio.com/resources/cheatsheets/ ; https://ugoproto.github.io/ugo_r_doc/basics_cs/

![https://ugoproto.github.io/ugo_r_doc/basics_cs/](https://ugoproto.github.io/ugo_r_doc/img/advanced_r_cs/AdvancedRa.png)

![https://ugoproto.github.io/ugo_r_doc/basics_cs/](https://ugoproto.github.io/ugo_r_doc/img/advanced_r_cs/AdvancedRb.png)

![https://ugoproto.github.io/ugo_r_doc/basics_cs/](https://ugoproto.github.io/ugo_r_doc/img/advanced_r_cs/AdvancedRc.png)

![https://ugoproto.github.io/ugo_r_doc/basics_cs/](https://ugoproto.github.io/ugo_r_doc/img/advanced_r_cs/AdvancedRd.png)

![https://ugoproto.github.io/ugo_r_doc/basics_cs/](https://ugoproto.github.io/ugo_r_doc/img/advanced_r_cs/AdvancedRe.png)

## stringr

## Basic Regular Expressions

## tidyverse

## ggplot2 : Data Visualization

## purrr : apply functions

## caret

## tidymodels

## keras

## devtools : Package Development